### PR TITLE
Fix order by multiple field with different orders and added Filter support.

### LINKED ISSUE #293: Support for Firestore OR queries
Hi!

I couldn't find any documentation or issues regarding support for Firestore OR queries using `Filter.or()`. Does fake_cloud_firestore have it already?

https://firebase.google.com/docs/firestore/query-data/queries#or_queries

Thank you for the amazing package!

### PR DESCRIPTION
**Pull request by ominibyte**
This PR addresses the following:
1. Fixes an issue when ordering by multiple fields with different sort orders
2. Closes #293 with support for Filter.or and Filter.and

### CODE REVIEW

**Comment by atn832** [comment]
Wow thank you for tackling these big issues! It's a shame you didn't split it into two PRs. It'll take me quite a bit longer to review.

**Comment by david-levio** [comment]
Yeah, I waited a week before adding the other. I needed them in my work so I had to merge them together.

File: lib/src/mock_query.dart [hunk 1]
```diff
@@ -71,59 +71,71 @@ class MockQuery<T extends Object?> extends FakeQueryWithParent<T> {
...
+        }
+        if (value2 == null) {
+          return 1;
+        }
+        final compare = value1.compareTo(value2);
+        return descending ? -compare : compare;
       }
+
+      sortedList.sort((d1, d2) {
+        var compare = doCompare(fields.first, directions.first, d1, d2);
```
Comment (atn832) [inline lib/src/mock_query.dart:130]: I guess it's just a matter of preference. This could work too and is sligthly more readable:
```dart
for (var i = 0; i < fields.length; i++) {
  final compare = doCompare(fields[i], directions[i], d1, d2);
  if (compare != 0) {
    return compare;
  }
}
return 0;
```

File: lib/src/mock_query.dart [hunk 2]
```diff
@@ -239,55 +251,182 @@ class MockQuery<T extends Object?> extends FakeQueryWithParent<T> {
...
-              isLessThanOrEqualTo: isLessThanOrEqualTo,
-              isGreaterThan: isGreaterThan,
-              isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
-              arrayContains: arrayContains,
-              arrayContainsAny: arrayContainsAny,
-              whereIn: whereIn,
-              whereNotIn: whereNotIn,
-              isNull: isNull);
-        }).toList();
+    if (field is Filter) {
```
Comment (atn832) [inline lib/src/mock_query.dart:254]: At first glance, it is a bit difficult to see that the only thing that changes is the predicate. We could rewrite it like so:
```dart
final predicate = field is Filter ?
  _buildFilterPredicate(field.toJson())
  : (document) => _wherePredicate(document, field,
      isEqualTo: isEqualTo,
      isNotEqualTo: isNotEqualTo,
      isLessThan: isLessThan,
      isLessThanOrEqualTo: isLessThanOrEqualTo,
      isGreaterThan: isGreaterThan,
      isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
      arrayContains: arrayContains,
      arrayContainsAny: arrayContainsAny,
      whereIn: whereIn,
      whereNotIn: whereNotIn,
      isNull: isNull)
final operation = (List<DocumentSnapshot<T>> docs) => docs
  .where(predicate)
  .toList();
return MockQuery<T>(this, operation);
```

File: lib/src/mock_query.dart [hunk 3]
```diff
@@ -239,55 +251,182 @@ class MockQuery<T extends Object?> extends FakeQueryWithParent<T> {
...
+            arrayContains: arrayContains,
+            arrayContainsAny: arrayContainsAny,
+            whereIn: whereIn,
+            whereNotIn: whereNotIn,
+            isNull: isNull))
+        .toList();
     return MockQuery<T>(this, operation);
   }
 
+  bool Function(DocumentSnapshot<T> document) _buildFilterPredicate(
```
Comment (atn832) [inline lib/src/mock_query.dart:276]: Very nice

Comment (atn832) [reply lib/src/mock_query.dart:276]: Perhaps explaining briefly in the method's docs how a Filter gets serialized to JSON could help others understand the code faster.

File: test/mock_query_test.dart
Comment (atn832) [inline test/mock_query_test.dart:1]: GitHub doesn't really show the preexisting tests above. So at first glance, it is not clear which tests were simply a copy/paste of existing tests with Filter applied, and which ones are novel. Pointing out the few ones that are novel would have helped me review.

File: test/mock_query_test.dart [hunk 4]
```diff
@@ -1269,6 +1705,64 @@ void main() {
     ]);
   });
 
+  test('orderBy with second field descending', () async {
```
Comment (atn832) [inline test/mock_query_test.dart:1708]: Awesome

File: test/mock_query_test.dart [hunk 5]
```diff
@@ -1923,4 +2417,98 @@ void main() {
...
+          ),
+          Filter.and(
+            Filter('name', isEqualTo: 'California'),
+            Filter('state', isEqualTo: 'California'),
+          ),
+        ))
+        .snapshots()
+        .listen(expectAsync1((QuerySnapshot snapshot) {
+      expect(snapshot.docs.length, equals(1));
+      expect(snapshot.docs.first.get('name'), equals('Washington'));
```
Comment (atn832) [inline test/mock_query_test.dart:2511]: 👍

**Review by atn832 — APPROVED** [review]
Thank you so much for your excellent PR!

**Comment by atn832** [comment]
I just published your code to https://pub.dev/packages/fake_cloud_firestore/changelog#310 and updated the README with the new features you implemented. Thanks again!

File: lib/src/mock_query.dart (hunk 1 above)
Comment (atn832) [reply lib/src/mock_query.dart:130]: I ended up making the change at https://github.com/atn832/fake_cloud_firestore/commit/57311c7816163cab22ee2e2686083ae6e1c385ad.

File: lib/src/mock_query.dart (hunk 2 above)
Comment (atn832) [reply lib/src/mock_query.dart:254]: I made the change at https://github.com/atn832/fake_cloud_firestore/commit/9af8832de35a8ff810a08210a8fded7b741bae83.

**Comment by ominibyte** [comment]
Thanks, I saw the changes you made and the published version.
