### PR TITLE
`DocumentReference.update` throws an exception when the document does not exist

### LINKED ISSUE #40: UpdateData should throw PlatformException if no existing document
As in the #39 's test case, updateData should throw PlatformException if there's no document.

https://github.com/atn832/cloud_firestore_mocks/pull/39/files#diff-bc4857fb99d367ed497ed395a5dfa274R98

```
flutter: 00:01 +7 -2: Firestore behavior comparison: Nested objects update (Cloud Firestore) [E]
flutter:   PlatformException(Error 5, FIRFirestoreErrorDomain, No document to update:
projects/flutter-firestore/databases/(default)/documents/messages/UYK7FkXENdf7mshYHrjR)
```

### PR DESCRIPTION
**Pull request by atn832**
Fixes #40 and #152.

### CODE REVIEW

File: lib/src/mock_collection_reference.dart [hunk 1]
```diff
@@ -159,17 +159,7 @@ class MockCollectionReference<T extends Object?> extends MockQuery<T>
...
-    if (data is Map<String, Object?>) {
-      await documentReference.update(data);
-    } else if (_converter != null) {
-      // Use the converter.
-      await documentReference.update(_converter!.toFirestore(data, null));
-    } else {
-      throw StateError('This should never happen');
-    }
-
+    await documentReference.set(data);
```
Comment (atn832) [inline lib/src/mock_collection_reference.dart:162]: `add` sets data for a new document, so we shouldn't use `update`.

File: test/fake_cloud_firestore_test.dart [hunk 2]
```diff
@@ -824,7 +839,7 @@ void main() {
     final foo = firestore.collection('users').doc('foo');
     await foo.set(<String, dynamic>{'name.firstName': 'OldValue Foo'});
     final bar = firestore.collection('users').doc('bar');
-    await foo.set(<String, dynamic>{'name.firstName': 'OldValue Bar'});
+    await bar.set(<String, dynamic>{'name.firstName': 'OldValue Bar'});
```
Comment (atn832) [inline test/fake_cloud_firestore_test.dart:842]: This was a pre-existing bug. I caught it when making `update` throw exceptions on non-existent documents. On line 831 below, bar was actually still unset and `batch.update(bar` threw an exception.

**Comment by atn832** [comment]
Published to https://pub.dev/packages/fake_cloud_firestore/changelog#124.

**Comment by atn832** [comment]
Note: we actually make the Future fail. Will switch to `throw`ing an exception if necessary.
